name = "SPH"
version = "0.2.0"
maintainer = "左志华"
license = "BSD-3 Clause"
copyright = "Copyright 2022 左志华"
description = "An open source smoothed particle hydrodynamics (SPH) project"

# fpm中文帮助文档: https://fpm.fortran-lang.org/zh_CN/spec/manifest.html
[build]
auto-executables = false
auto-tests = false
auto-examples = false

[dependencies]
info = { git = "https://gitee.com/zoziha/info.git" }
easy_lua = { git = "https://gitee.com/zoziha/easy-lua.git" }
easy_math = { git = "https://gitee.com/zoziha/easy_math.git" }
swift_file = { git = "https://gitee.com/zoziha/swift_file.git" }
error_stop = { git = "https://gitee.com/zoziha/error_stop.git" }
master_time = { git = "https://gitee.com/zoziha/master_time.git" }
easy_string = { git = "https://gitee.com/zoziha/easy_string.git" }
progress_bar = { git = "https://gitee.com/zoziha/progress_bar.git" }
stdlib_logger = { git = "https://gitee.com/zoziha/stdlib_logger.git" }
argv-fortran = { git="https://gitee.com/fortran-base/argv-fortran.git" }

ntree = { git = "https://gitee.com/zoziha/ntree.git" }
toml-f = { git = "https://gitee.com/fortran-base/toml-f.git" }


[dev-dependencies]
test-drive = { git = "https://gitee.com/fortran-base/test-drive", tag = "v0.4.0" }

[[executable]]
name = "sph"
main = "sph.f90"
source-dir = "app"

[[test]]
name = "tester"
main = "tester.f90"
source-dir = "test"
