name = "SPH"
version = "VERSION"
maintainer = "左志华"
license = "BSD-3 Clause"

[build]
auto-executables = false
auto-tests = false
auto-examples = false

[library]
include-dir = "src"

[[executable]]
name = "sph"
main = "sph.f90"
source-dir = "app"

[[executable]]
name = "vtk"
main = "to_vtk.f90"

[[test]]
name = "tester"
main = "tester.f90"
source-dir = "test"
